version: '3.9'

services:
  db:
    build: 
      context: ./db
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data

  db_api:
    build: 
      context: ./db-api
    env_file:
      - .env
    ports:
      - "5995:5995"
    depends_on:
      db:
        condition: service_started
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}

volumes:
  db_data:

